<template>
  <div class="container">
    <router-link tag="a" class="logoContainer" :to="{ name: 'Landing' }">
      <img src="../../../assets/images/floating_logo.svg" class="ampersandLogo" />
      <img src="../../../assets/images/sons_logo.svg" class="sonsLogo" />
    </router-link>

    <section class="privacy-section">
      <h1>andSons Terms Of Service</h1>
      <article>
        <h2>GENERAL</h2>

        <p>
          1.1. This document is an electronic record & being generated by a computer system it does not require any
          physical or digital signatures.
        </p>
        <p>
          1.2. This document is published to provide the rules and regulations, privacy policy and Terms of Use for
          access or usage of andSons.com.sg or the application “andSons’.
        </p>
        <p>
          1.3. The domain name andSons.com.sg (hereinafter referred to as ‘Website’)is owned by PX Ventures Pte. Ltd.
          (hereinafter referred to as ‘Company’).
        </p>
        <p>
          1.4. For the purpose of these Terms of Service, wherever the context so requires the term ‘You’/ ‘User’ shall
          mean any natural or legal person who has downloaded and installed this Mobile Application (hereinafter
          referred to as ‘App’) and provided Registration Data while registering on the App or by simply visiting the
          Website by entering the domain name in any internet browser. If you are an individual who is entering into
          these Terms on behalf of an entity, you represent and warrant that you have the power to bind that entity, and
          you hereby agree on that entity’s behalf to be bound by these Terms, with the terms “you,” and “your” applying
          to you, that entity, and other users accessing the Service on behalf of that entity.Any services provided by
          the Website/App which do not require registration do not absolve You of the contractual relationship
          established by this Agreement.
        </p>

        <p>
          1.4.1. By visiting the website, You are bound by these Terms of Service and any other binding documents as
          decided by the Company. You are requested to read them carefully before accepting the same and moving forward
          to using the App.
        </p>
        <p>
          1.4.2. The term ‘We’/ ‘Us’/ ‘Our’ shall mean www.andsons.com.sg and our mobile application andSons. The use of
          this App by You is solely governed by this Terms of Service and any other terms or policies published by Us.
          Moving past the home page of the Website or downloading the App and using any of the services shall be taken
          to mean that You have read and agreed to all of the terms and conditions so binding on You as laid down in
          these terms.
        </p>
        <p>
          1.4.3. You will be subject to the rules, guidelines, policies, terms, and conditions as applicable to any
          service that is provided by this App, and they shall be deemed to be incorporated into this Terms of Service
          and shall be considered as part and parcel of this Terms of Service. We hold the sole right to modify the
          Terms of Service without prior permission from You or informing You.
        </p>
        <p>
          1.4.4. This relationship with Us creates on You a duty to periodically check the terms and stay updated with
          its requirements. If You continue to use the Website/App following such a change, this is deemed as
          unequivocal consent by You to the so amended policies by Us. As long as You comply with these Terms of Use, We
          grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the App.
        </p>
        <p>
          1.4.5. Through the Website, Users select a specialty (e.g. Men’s Health). After that, the User can either see
          a Medical Professional immediately or Schedule an appointment for later time. The Medical Professional will be
          allocated to the User based on availability.
        </p>
        <p>
          1.4.6. We are not liable to any records, data, pictures or documents submitted by any other means such as
          personal email, mobile, sms or any messaging platform.
        </p>
        <p>
          1.4.7. This App/Website is also aimed at assisting Medical Professionals to provide services to patients that
          have registered on the App/ Website. The Medical Professional who wishes to provide services on the App/
          Website has to be verified before joining by providing proper documentation which shall be authenticated by
          the Company. Only upon authentication and approval shall a Medical Professional be enlisted on the App/
          Website.
        </p>
        <p>
          1.4.8. By impliedly or expressly accepting these Terms of Service, You also accept and agree to be bound by
          other Company Policies and rules and regulations, inter alia, the Privacy Policy, which also, would be amended
          from time to time.
        </p>

        <h2>MEMBERSHIP/USAGE</h2>

        <p>
          2.1. The membership/usage of the Website/App is restricted to those above 18 years of age, or to such group
          that can be termed to have attained 'majority' under the laws of the respective jurisdictions where this
          Website/App can be seen and is accessible or to emancipated minors, who possess legal parental or guardian
          consent, or are in a position so as to be fully able and competent to enter into the terms, conditions,
          obligations, affirmations, representations, and warranties set forth in these Terms of Service, and to abide
          by and comply with these Terms of Service.
        </p>
        <p>
          2.2. Further, You are solely responsible for protecting the confidentiality of your username and password and
          any activity under the account will be deemed to have been done by You. In the event that We discovered that
          You have provided us with false and inaccurate details, We hold the rights to suspend Your account and/or
          terminate this Agreement without being held liable for the such termination and/or suspension.
        </p>
        <p>
          2.3. You understand the App downloaded on to your phone or tablet is owned by Us and We may automatically
          upgrade the App and these Terms shall apply to the upgrades as well.
        </p>

        <h2>COMMUNICATIONS AND INFORMATION SHARING</h2>

        <p>
          3.1. By using this Website/App, it is deemed that You have consented to receiving calls, auto-dialled and/or
          pre-recorded messages or calls, from Us at any time with the use of the telephone number that has been
          provided by You for the use of this Website/App, subject to the Privacy Policy. This includes contacting You
          through information received through other parties as well as contacting other parties through the information
          You provide to Us.
        </p>
        <p>
          3.2. The use of this Website/App is also Your consent to receive communications (e.g. SMSes, Emails, etc) from
          Us at any time We deem fit. This consent to be contacted is for purposes that include and are not limited to
          clarification calls and marketing communications. In case You wish to stop contact with Us for the same, You
          may send Us an email to the effect at hello@andsons.com.sg
        </p>
        <p>
          3.3. You may also be contacted by Service Providers with whom We have entered into a contract in furtherance
          of Our rights, duties and obligations under other agreements, contracts and policies followed by Us. Such
          contact will be made only in pursuance of the respective contract agreements and/or policies.
        </p>
        <p>
          3.4. The sharing of the information provided by You will govern by the Privacy Policy. We will not give out
          such Your contact information to third parties not connected with the Website/App and the services offered by
          it, and/or for any purpose not in furtherance of the activities and aims of the Company. Please refer to the
          'Privacy Policy' for more information.
        </p>

        <h2>PAYMENT</h2>

        <p>
          4.1. The installation and use of this Website/App is free of cost and this includes only the usage of certain
          services of the Website/App. You hereby understand and accept that the free/complimentary services may be
          amended any time at the discretion of the Company.
        </p>
        <p>
          4.2. However, in the event You use the App/Website for a payable services such as consultation with Medical
          Professional or buying medication, You shall be required to pay for the consult as stated in the payment page
          at the time of usage and in the event that medication(s) is prescribed by a Medical Professional, you shall be
          required to pay for the medication(s) in the payment page if you would like to procure the medication(s),
          alongside delivery costs where applicable.
        </p>
        <p>
          4.3. For the purpose of this section, Buyer would include any Users choosing to use the services offered on
          our Website/App. Seller means Us/Website/Company.
        </p>
        <p>
          4.4 All prices listed for payable services in the Website/App by us are subject to change and You hereby
          understand and accept that we reserve the right to change, modify and/or amend the price listed at any time
          without prior notice. Any discount codes for prices listed in the Website/App given and/or caused to be given
          by us are not applicable to prescription products. Such prescription products include all pharmaceutical
          and/or drug products that are required to be licensed medical practitioner or pharmacist in Singapore. You
          understand prescription products listed in Website/App cannot be used in conjunction with any ongoing
          promotions and are not refundable or exchangeble for cash or otherwise.
        </p>
        <p>
          4.5. While availing any of the payment method(s) available on the Website/App, We shall not be responsible or
          assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due
          to:
        </p>
        <p>
          4.4.1. Lack of authorization for any transaction(s), or
        </p>
        <p>
          4.4.2. Exceeding the preset limit mutually agreed by You and ‘Bank(s)’ or financial service provider, or
        </p>
        <p>
          4.4.3. Any payment issues arising out of the transaction, or
        </p>
        <p>
          4.4.4. Decline of transaction for any other reason(s)
        </p>

        <h2>THIRD PARTY INFORMATION</h2>

        <p>
          5.1. The content on the Website/App which includes all text, graphics, user interfaces, visual interfaces,
          photographs, trademarks, logos, sounds, music, design documents, and artwork is Our content (hereinafter
          referred to as ‘Content’).
        </p>
        <p>
          5.2. The Website/App may contain links to/ content of third party websites that are not associated with us. We
          have no control over any third party user generated content as We are merely an intermediary for the purposes
          of those content.
        </p>
        <p>
          5.3. In the event, if any of the Third Party Content infringes any Intellectual Property of any person, the
          Third Party shall be solely responsible for any loss caused and We shall not be liable. You may send as an
          email hello@andsons.com.sg to report any such content.
        </p>
        <p>
          5.4. Other than when expressly allowed, any use of Our Content and it being reproduced, republished, uploaded,
          posted, publicly displayed, encoded, translated, transmitted or distributed in any way (including "mirroring"
          or duplicating data to another computer or device) to any other computer, server, website or other medium for
          publication or distribution or for any commercial enterprise, without Our express prior written consent is not
          allowed.
        </p>

        <h2>USER CONTENT</h2>

        <p>
          6.1. The content that You upload or post will become Our property and You grant Us the worldwide, perpetual
          and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as
          adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever,
          including but not limited to promotional and advertising purposes and in any media whether now known or
          hereafter devised, including the creation of derivative works that may include any content You provide and are
          not entitled to any payment or other compensation for such use. You also grant Us the right to sub-license
          these rights, and the right to bring an action for infringement of these rights. We reserve the right to edit
          or remove any material at any time submitted to this Website/App, or stored on Our servers, or hosted or
          published upon this Website/App.
        </p>
        <p>
          6.2. Any posting by You of any form of User content on the Website/App must be verified as to the truthfulness
          and authenticity of the particulars of the content, including the time, place and nature. Before allowing such
          content to be posted on the Website/App, We have the right and authority to verify the accuracy of such
          particulars related to the content with the respective sources provided by the User posting such content, in
          the event that We deem it necessary to check such accuracy.
        </p>
        <p>
          6.3. We have the right to upload content on behalf of third parties, subsequent to collecting such information
          and verifying it if we deem it necessary. Notwithstanding this, We can in no way be held liable for any false
          or misleading information.
        </p>
        <p>
          6.4. In case any content is considered to be unlawful or against the law within any jurisdiction in which Our
          Website/App can be seen and accessed, it shall be removed forthwith by Us on being intimated by the
          authorities of the respective jurisdiction that such content is deemed unlawful. We cannot be held liable or
          questioned for the same.We reserve to right to pursue legal action for indemnity, losses and/or damages
          against You arising out of any posting of User content by You.
        </p>

        <h2>USER OBLIGATIONS</h2>

        <p>
          7.1. You are a restricted user of this Website/App.
        </p>
        <p>
          7.2. You shall not cut, copy, distribute, modify, recreate, reverse engineer, distribute, disseminate, post,
          publish or create derivative works from, transfer, or sell any information or software obtained from the
          Website/App.
        </p>
        <p>
          7.3. With Our prior permission limited use of this Website/App may be allowed. For the avoidance of doubt, it
          is clarified that unlimited or wholesale reproduction, copying of the content for commercial or noncommercial
          purposes and unwarranted modification of data and information within the content of the Website/App is not
          permitted.
        </p>
        <p>
          7.4. You shall not, nor allow third parties on Your behalf to (i) make and distribute copies of the
          Website/App (ii) attempt to copy, reproduce, alter, modify, reverse engineer, disassemble, decompile,
          transfer, exchange or translate the Website/App; or (iii) create derivative works of the Website/App of any
          kind whatsoever.
        </p>
        <p>
          7.5. You agree not to access (or attempt to access) the Website/App and/or the materials or Services by any
          means other than through the interface that is provided by the Website/App.
        </p>
        <p>
          7.6. The use of deep-link, robot, spider or other automatic device, program, algorithm or methodology, or any
          similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Website/App or
          Content, or in any way reproduce or circumvent the navigational structure or presentation of the Website/App,
          materials or any Content, to obtain or attempt to obtain any materials, documents or information through any
          means not specifically made available through the Website
        </p>
        /App.
        <p>
          7.7. You acknowledge and agree that by accessing or using the Website/App or Services, You may be exposed to
          content from other users that You may consider offensive, indecent or otherwise objectionable.
        </p>
        <p>
          7.8. We disclaim all liabilities arising in relation to such offensive content on the Website/App. Further,
          You may report such offensive content by sending us an e-mail to hello@andsons.com.sg.
        </p>
        <p>
          7.9. This Website/App by nature allows you to upload information; You undertake to ensure that such material
          is in accordance with applicable laws. Further, You undertake not to:
        </p>
        <p>
          7.9.1. Abuse, harass, threaten, defame, disillusion, erode, abrogate, demean or otherwise violate the legal
          rights of others;
        </p>
        <p>
          7.9.2. Engage in any activity that interferes with or disrupts access to the Website/App or the Services (or
          the servers and networks which are connected to the Website/App);
        </p>
        <p>
          7.9.3. Impersonate any person or entity, or falsely state or otherwise misrepresent Your affiliation with a
          person or entity;
        </p>
        <p>
          7.9.4. Publish, post, disseminate, any information which is grossly harmful, harassing, blasphemous,
          defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or
          racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or
          otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing;
        </p>
        <p>
          7.9.5. Post any file that infringes the copyright, patent or trademark of other legal entities.
        </p>
        <p>
          7.9.6. Upload or distribute files that contain viruses, corrupted files, or any other similar software or
          programs that may damage the operation of the Website/App or another's computer;
        </p>
        <p>
          7.9.7. Download any file posted by another user of a Service that you know, or reasonably should know, cannot
          be legally distributed in such manner;
        </p>
        <p>
          7.9.8. Probe, scan or test the vulnerability of the Website/App or any network connected to the Website/App,
          nor breach the security or authentication measures on the Website/App or any network connected to the
          Website/App. You may not reverse look-up, trace or seek to trace any information on any other user, of or
          visitor to, the Website/App, or any other customer of the Website/App, including any account not owned by You,
          to its source, or exploit the Website/App or Service or information made available or offered by or through
          the Website/App, in any way whether or not the purpose is to reveal any information, including but not limited
          to personal identification information, other than Your own information, as provided for by the Website/App;;
        </p>
        <p>
          7.9.9. Disrupt or interfere with the security of, or otherwise cause harm to, the Website/App, systems
          resources, accounts, passwords, servers or networks connected to or accessible through the Website/App or any
          affiliated or linked sites;
        </p>
        <p>
          7.9.10. Collect or store data about other users in connection with the prohibited conduct and activities set
          forth in this Section.
        </p>
        <p>
          7.9.11. Use the Website/App or any material or Content for any purpose that is unlawful or prohibited by these
          Terms of Service, or to solicit the performance of any illegal activity or other activity which infringes the
          rights of this Website/App or other third parties;
        </p>
        <p>
          7.9.12. Violate any code of conduct or other guidelines, which may be applicable for or to any particular
          Service;
        </p>
        <p>
          7.9.13. Violate any applicable laws or regulations for the time being in force within or outside Singapore;
        </p>
        <p>
          7.9.14. Violate the Terms of Service including but not limited to any applicable Additional Terms of the
          Website/App contained herein or elsewhere;
        </p>
        <p>
          7.9.15. Threaten the unity, integrity, defence, security or sovereignty of Singapore, friendly relations with
          foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents
          investigation of any offence or is insulting any other nation.
        </p>
        <p>
          7.9.16. Publish, post, disseminate information that is false, inaccurate or misleading; violate any applicable
          laws or regulations for the time being in force in or outside Singapore;
        </p>
        <p>
          7.9.17. Directly or indirectly, offer, attempt to offer, trade or attempt to trade in any item, the dealing of
          which is prohibited or restricted in any manner under the provisions of any applicable law, rule, regulation
          or guideline for the time being in force.
        </p>
        <p>
          7.9.18. Create liability for Us or cause Us to lose (in whole or in part) the services of Our internet service
          provider ("ISPs") or other suppliers;
        </p>
        <p>
          7.10. While We shall not be held liable or answerable to Users for any such acts on Your part, violation of
          this clause would lead to potential criminal legal action against You, either by other Users of the Website or
          by Us. We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement
          or other government officials, as We, in Our sole discretion, believe necessary or appropriate in connection
          with the investigation and/or resolution of possible crimes, especially those that may involve personal
          injury.
        </p>
        <p>
          7.11. You understand that We have the right at all times to disclose any information (including the identity
          of the persons providing information or materials on the Website/App) as necessary to satisfy any law,
          regulation or valid governmental request. This may include, without limitation, disclosure of the information
          in connection with investigation of alleged illegal activity or solicitation of illegal activity or in
          response to a lawful court order or subpoena.
        </p>
        <p>
          7.12. We have no obligation to monitor the material posted on the Website/App. We shall have the right to
          remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law
          or either the spirit or letter of these Terms of Service. Notwithstanding this right, YOU SHALL REMAIN SOLELY
          RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE WEBSITE/APP.
        </p>
        <p>
          7.13. In no event shall We assume or have any responsibility or liability for any Content posted or for any
          claims, damages or losses resulting from use of Content and/or appearance of Content on the App.
        </p>
        <p>
          7.14. You hereby represent and warrant that You have all necessary rights in and to all Content which You
          provide and all information it contains and that such Content shall not infringe any proprietary or other
          rights of third parties or contain any libelous, tortuous, or otherwise unlawful information.
        </p>

        <h2>CANCELLATIONS AND REFUNDS</h2>

        <p>
          8.1. The Website/App shall be only an intermediary connecting the User with the Medical professional of the
          service booked. Once the appointment has been made and a confirmation has been given to the User, the Company
          shall inform the Medical Professional who shall render their consultation at the agreed time, location and
          mode provided at the time of booking the service. This includes procurement of medication(s) prescribed by a
          Medical Professional and subsequent medication(s) delivery to User as well.
        </p>
        <p>
          8.2. Once an appointment has been made and it is confirmed at Our end, no amount shall be refunded, in the
          event of a cancellation initiated by the User. In the event that medication(s) is prescribed by a Medical
          professional and User decides to procure the medication(s) and the order is confirmed at Our end, no amount
          shall be refunded, in the event of a cancellation initiated by the User.
        </p>
        <p>
          8.3. However, in certain circumstances, the Company, at its sole discretion, shall permit a refund of the full
          or partial amount if the Medical professional becomes unavailable, if an alternative Medical professional is
          arranged to consult or no suitable medication(s) substitute is available for dispensation (including delivery
          costs where applicable). The decision of the Company shall be final in such cases.
        </p>
        <p>
          8.4 In the event that We modify, change and/or amend the prices listed for payable services in Website/App
          during Your subscription cycle in accordance with the terms herein, We shall not permit a fund whether in full
          or partial and the any change, modification or amendment made to the prices listed shall only be reflected in
          in the next subscription cycle.
        </p>

        <h2>LOCATION</h2>

        <p>
          9.1. Currently We provide chat, phone call, video call and medication delivery services in Singapore.
        </p>

        <h2>DISCLAIMERS</h2>

        <p>
          10.1. You understand that the Website/App is a platform that Users utilize to seek medical consultation locate
          and make appointments for chat, phone or video consult. Even though We take all the necessary steps to verify
          the authenticity of the Medical professionals, You understand that We shall not be liable for any deficiencies
          including but not limited to misconduct, injury caused or lack of knowledge from the end of the Medical
          professional. We are not a party to such interaction and assume no liability that arises from any such acts of
          the Medical professional.
        </p>
        <p>
          10.2. Healthcare Services
        </p>
        <p>
          10.2.1. All of the Medical Professionals who deliver Services through andSons are independent Medical
          Professionals solely responsible for the services each provides to you.
        </p>
        <p>
          10.2.2. andSons does not practice medicine or any other licensed profession, and does not interfere with the
          practice of medicine or any other licensed profession by a Medical professional, each of whom is responsible
          for his or her services and compliance with the requirements applicable to his or her profession and license.
        </p>
        <p>
          10.2.3. Neither andSons nor any third parties related/affiliated to andSons who promote the Services or
          provide you with a link to the Service shall be liable for any professional advice you obtain from a Medical
          professional via the Services.
        </p>
        <p>
          10.3. Informed Consent:
        </p>
        <p>
          10.3.1. andSons provides a platform to deliver health care services using interactive audio and video
          technology, where the patient and the medical professional are not in the same physical location. During your
          telehealth consultation with a medical professional, details of your health history and personal health
          information may be discussed with you through the use of interactive video, audio and other telecommunications
          technology, and your medical professional may perform a physical examination through these technologies
        </p>
        <p>
          10.3.2. The telehealth Services you receive from Medical Professional are not intended to replace a primary
          care physician relationship or be your permanent medical home.
        </p>
        <p>
          10.3.3. You should seek emergency help or follow-up care when recommended by a Medical Professional or when
          otherwise needed, and continue to consult with your primary care physician and other medical professionals as
          recommended.
        </p>
        <p>
          10.3.4. You will have direct access to customer support services to follow up on medication reactions, side
          effects or other adverse events.
        </p>
        <p>
          10.3.5. Among the benefits of our Services are improved access to healthcare professionals and convenience.
          However, as with any health service, there are potential risks associated with the use of telehealth. These
          risks include, but may not be limited to:
        </p>
        <p>
          10.3.5.1. In rare cases, information transmitted may not be sufficient (e.g. poor resolution of images) to
          allow for appropriate health care decision making by the Medical Professional;
        </p>
        <p>
          10.3.5.2.Delays in evaluation or treatment could occur due to failures of the electronic equipment. If this
          happens, you may be contacted by phone or other means of communication.
        </p>
        <p>
          10.3.5.3.In rare cases, a lack of access to all of your health records may result in adverse drug interactions
          or allergic reactions or other judgment errors;
        </p>
        <p>
          10.3.5.4.Although the electronic systems we use will incorporate network and software security protocols to
          protect the privacy and security of health information, in rare instances, security protocols could fail,
          causing a breach of privacy of personal health information
        </p>
        <p>
          10.3.6 By accepting these Terms of Use, you acknowledge that you understand and agree with the following:
        </p>
        <p>
          10.3.6.1. You understand that you may expect the anticipated benefits from the use of telehealth in your care,
          but that no results can be guaranteed or assured.
        </p>
        <p>
          10.3.6.2. You understand that the laws that protect the privacy and security of health information apply to
          telehealth, and have received andSons’s Notice of Privacy Practices, which describes these protections in more
          detail.
        </p>
        <p>
          10.3.6.3. Electronic communications are directed to your Medical Professional (s) and their supervisees
          through a secure, encrypted video interface and electronic health record.
        </p>
        <p>
          10.3.6.4. Your Medical Professional may determine that the Services are not appropriate for some or all of
          your treatment needs, and accordingly may elect not to provide telehealth services to you through the Site.
        </p>
        <p>
          10.4. All communication between the Medical professional and You is a separate transaction which includes
          without any limitation all warranties related to consult and after consult services related to consult. We do
          not have any control over such information and play no determinative role in the finalization of the same and
          hence do not stand liable for the outcomes of such communication.
        </p>
        <p>
          10.5. We shall ensure that all Medical Professionals providing audio/video consultation and e-prescription are
          fully qualified and registered with the Singapore Medical Council (SMC) and in possession of valid Annual
          Practicing Certificate (APC).
        </p>
        <p>
          10.6. For complimentary chat service, most inquiries and basic chats will be handled by our patient care
          consultants. Patient care consultants are tasked to answer your basic questions for screening purposes before
          proceeding to medical consultation with the Medical Professional. Any information provided by the patient care
          consultant should not be deemed as medical advice.
        </p>
        <p>
          10.7. We do not endorse any specific Medical Professional on the App nor place any guarantee as to its quality
          and value. Any such recommendations that are done are done by other users and the Company does not verify or
          acknowledge the same.
        </p>
        <p>
          10.8. Further We may suggest apt treatments or services in accordance with the/ your information within our
          knowledge but We do not guarantee any effectiveness or success upon using these services.
        </p>
        <p>
          10.9. Subject to the above sub-clauses, a contract exists between the Medical professional and You and as such
          any breach of contract and thus, any claim arising from such breach is the subject matter of the Medical
          professional and You alone and We are in no way a party to such breach or involved in any suit arising from
          the same breach.
        </p>
        <p>
          10.10. The content on the Website and App is general in nature and summarized, and is provided for
          informational purposes only. The content of the Website and App, including without limitation, text, copy,
          audio, video, photographs, illustrations, graphics and other visuals, is for informational purposes only and
          does not constitute professional advice, or recommendations of any kind.
        </p>
        <p>
          10.11. Reliance on any content provided on website/app or any links on andSons website/app is solely at your
          own risk. We reserve the right to change or discontinue, at any time, any aspect or feature of this
          website/app.
        </p>
        <p>
          10.12. You do hereby grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty- free,
          sub-licensable right to exercise the copyright, publicity, and database rights you have in Your information,
          in any media now known or not currently known, with respect to Your information to enable Us to use the
          information for the purpose of providing the Services
        </p>
        <p>
          10.13. You do hereby unconditionally and irrevocably agree to give consent to Us to collect, hold, use,
          delete, disclose, transfer, administer, store and process (within or outside Singapore) in any other way, all
          your personal data (including sensitive personal data and personal data of other party provided by you) given
          now or that is subsequently obtained from time to time, which may include but not limited to your name, NRIC
          number/Passport number, contact information, medical related information for our internal use and records.
        </p>
        <p>
          10.14. You do hereby unconditionally and irrevocably agree to give consent to Us to disclose and release your
          personal data to third party service providers, agents and other organisations we have engaged to perform any
          of the functions and services for you.
        </p>
        <p>
          10.15. You do hereby unconditionally and irrevocably agree to give consent to Us to disclose and release your
          personal data for any purpose required by law or regulations.
        </p>
        <p>
          10.16. You release and indemnify Us and/or any of its officers and representatives from any cost, damage,
          liability or other consequence of any of the actions of the Users of the Website/App and specifically waive
          any claims that You may have in this behalf under any applicable law. You understand and accept that there
          could be risks in dealting with persons who are underage or acting under false pretense.
        </p>
        <p>
          10.17 By accepting the terms herein, you do hereby unconditionally and irrevocably agree to give consent to
          our licensed clinic, telehealth service or pharmacist appointed by Us for the delivery of prescription
          medication and/or products via postage or other modes of delivery.
        </p>

        <h2>COMPLIANCE WITH LAWS</h2>

        <p>
          11.1. The User of the Website/App shall comply with all the applicable laws applicable to them respectively
          for using Payment Facilities and the website
        </p>

        <h2>DISCLAIMER OF WARRANTIES AND LIABILITIES</h2>

        <p>
          12.1.You expressly understand and agree that, to the maximum extent permitted by applicable law:
        </p>
        <p>
          12.1.1. The website, services and other materials provided by this website is on an "as is" basis without
          warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title,
          non-infringement, merchantability or fitness for a particular purpose. Without limiting the foregoing, we make
          no warranty that:
        </p>
        <p>
          12.1.1.1. Your requirements will be met or that services provided will be uninterrupted, timely, secure or
          error-free;
        </p>
        <p>
          12.1.1.2. Materials, information obtained and results will be effective, accurate or reliable;
        </p>
        <p>
          12.1.1.3. Any errors or defects in the website, services or other materials will be corrected
        </p>
        <p>
          12.1.2. we will have no liability related to user content arising under intellectual property rights, libel,
          privacy, publicity, obscenity or other laws. We also disclaim all liability with respect to the misuse, loss,
          modification or unavailability of any user content.
        </p>
        <p>
          12.1.3. The user understands and agrees that any material or data downloaded or otherwise obtained through the
          website is done entirely at their own discretion and risk and they will be solely responsible for any damage
          to their computer systems or loss of data that results from the download of such material or data.
        </p>
        <p>
          12.1.4. We are not responsible for any typographical error leading to an invalid coupon. We accept no
          liability for any errors or omissions, with respect to any information provided to you whether on behalf of
          itself or third parties
        </p>
        <p>
          12.1.5. we shall not be liable for any third party product or services.
        </p>

        <h2>INDEMNIFICATION AND LIMITATION OF LIABILITY</h2>

        <p>
          13.1. You agree to indemnify, defend and hold harmless this website including but not limited to its affiliate
          vendors, agents and employees from and against any and all losses, liabilities, claims, damages, demands,
          costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable
          thereon) asserted against or incurred by us that arise out of, result from, or may be payable by virtue of,
          any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be
          performed by you pursuant to these terms of use.
        </p>
        <p>
          13.2. Further, you agree to hold us harmless against any claims made by any third party due to, or arising out
          of, or in connection with, your use of the website, any claim that your material caused damage to a third
          party, your violation of the terms of service, or your violation of any rights of another, including any
          intellectual property rights in no event shall we, or our officers, directors, employees, partners or
          suppliers be liable to you or any third party for any special, incidental, indirect, consequential or punitive
          damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or
          whether or not we have been advised of the possibility of such damages, or based on any theory of liability,
          including breach of contract or warranty, negligence or other tortious action, or any other claim arising out
          of or in connection with your use of or access to the website, services or materials.
        </p>
        <p>
          13.3. The limitations and exclusions in this section apply to the maximum extent permitted by applicable law.
        </p>

        <h2>SEVERABILITY</h2>

        <p>
          14.1. If a provision of these terms and conditions is determined by any court or other competent authority to
          be unlawful and/or unenforceable, the other provisions will continue in effect. If any unlawful and/or
          unenforceable provision would be lawful or enforceable if part of it were deleted, that part will be deemed to
          be deleted, and the rest of the provision will continue in effect.
        </p>

        <h2>BREACHES OF THESE TERMS AND CONDITIONS</h2>

        <p>
          15.1. Without prejudice to our other rights under these Terms of Use, Your rights under the Agreement may
          automatically terminate without notice if You fail to comply with its terms.. We may terminate the Agreement
          or restrict, suspend or terminate Your access to the website or Your use of the Service at Our discretion
          without notice at any time and/or bringing court proceedings against You, including if We determine that Your
          use violates the Agreement, is improper, substantially exceeds or differs from normal use by other users, or
          otherwise involves fraud or misuse of the Service or harms our interests or those of another user of the
          Service or of a Third Party.
        </p>

        <h2>NO WAIVER</h2>

        <p>
          16.1. Our failure to insist upon or enforce your strict compliance with the Agreement will not constitute a
          waiver of any of our rights.
        </p>

        <h2>DISPUTE RESOLUTION</h2>

        <p>
          17.1. These Terms of Service will be governed by and construed in accordance with the laws of Singapore
          without regard to its conflicts of law provisions. Any failure of the Website/App/ Company to enforce or
          exercise any provision of this Agreement or related right shall not constitute a waiver of that right or
          provision. The section titles used in this Agreement are purely for convenience and carry with them no legal
          or contractual effect. In the event of termination of this Agreement for any reason, you agree the following
          provisions will survive: the provisions regarding limitations on your use of Content, the license(s) you have
          granted to the Website/App/Company, and all other provisions for which survival is equitable or appropriate
        </p>
        <p>
          17.2. In the case of a conflict between these terms and the terms of any electronic or machine readable
          statement or policy, these Terms of Service shall control. Similarly, in case of a conflict between these
          terms and our Privacy Policy, these Terms of Service shall control.
        </p>
        <p>
          17.3. The Parties expressly agree that the Terms, Policy and any other agreements entered into between the
          Parties are governed by the laws, rules and regulations of Singapore, and shall have exclusive jurisdiction
          over any disputes arising between the Parties
        </p>

        <h2>MISCELLANEOUS</h2>

        <p>
          18.1. We reserve the right to change these Terms of Service at any time in its discretion and to notify users
          of any such changes solely by changing these Terms of Service. Your continued use of the Website/App after the
          posting of any amended Terms of Service shall constitute your agreement to be bound by any such changes.
        </p>
        <p>
          18.2. Your use of this Website/App prior to the time this Terms of Service was posted will be governed
          according to the Terms of Service that applied at the time of your use. We may modify, suspend, discontinue or
          restrict the use of any portion, including the availability of any portion of the Content at any time, without
          notice or liability.
        </p>
        <p>
          18.3. We may deny access to any person or user at any time for any reason. In addition, we may at any time
          transfer rights and obligations under this Agreement to any affiliate, subsidiary or business unit, or any of
          their affiliated companies or divisions, or any entity that acquires Us or any of their assets.
        </p>
        <p>
          18.4 We hereby reserve the right to block usage of the Website/App if any breach of the Terms of Service is
          caused by a User. This can in no way be construed as a waiver of any legal right under Singaporean law to
          claim any damages or initiate any legal proceedings against the User.
        </p>

        <p>Last updated: 16 Apr 2021</p>
      </article>
    </section>

    <!-- <privacy-and-policy-footer></privacy-and-policy-footer> -->
  </div>
</template>

<script>
// import TheHeader from "../components/TheHeader";
// import PrivacyAndPolicyFooter from '../components/Privacy&PolicyFooter'
import { formatMetaTags } from '@/utils/prettify.js'

export default {
  components: {
    // TheHeader,
    // PrivacyAndPolicyFooter
  },
  metaInfo: formatMetaTags({
    title: 'Terms & Conditions',
    urlPath: 'terms-&-conditions'
  })
}
</script>

<style scoped lang="scss">
.container {
  background-color: $springwood-background;
  // overflow-y: scroll !important;
  // scroll-behavior: auto;
  // scrollbar-width: 10px;
}

h1 {
  font-family: 'PublicSansExtraBold', sans-serif;
  font-size: 2rem;
}

h2 {
  font-family: 'PublicSansSemiBold', sans-serif;
  color: $bismark-text;
  padding: 2rem 0;
  font-size: 1.125rem;
}

h2 {
  font-family: 'PublicSans', sans-serif;
  color: $apricot-text;
  padding-bottom: 1rem;
  font-size: 1.125rem;
}

article {
  padding: 1rem 0;
}

p,
li {
  font-family: 'PublicSans', sans-serif;
  font-size: 0.9rem;
  line-height: 1.3rem;
  word-wrap: break-word;
}

ol[type='a'],
ol[type='i'] {
  counter-reset: list;

  & > li {
    list-style: none;
  }

  & > li::before {
    font-size: 14px !important;
    counter-increment: list;
    display: inline-block;
    width: 50px;
    letter-spacing: 0;
  }
}

ol[type='i'] {
  & > li::before {
    content: '(' counter(list, lower-roman) ')';
  }
}

ol[type='a'] {
  & > li::before {
    content: '(' counter(list, lower-alpha) ')';
  }
}

p + *,
ol + * {
  padding-top: 1.3rem;
}
</style>
